name: Deploy prod site on push

on: 
  push:
    branches: 
      - master
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    steps:      
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      working-directory: ./StiffSong.Frontend
      run: npm install

    - name: Build Project
      working-directory: ./StiffSong.Frontend
      run: npm run build
    
    - name: Sync Files      
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: '${{ secrets.FTP_URL }}'
        username: '${{ secrets.FTP_USER }}'
        password: '${{ secrets.FTP_PASSWORD }}'
        local-dir: ./StiffSong.Frontend/dist/
        server-dir: ./stiff.cz/WWWRoot/wwwroot/
        dangerous-clean-slate: true
